services:
  # reverse proxy in front of boundary
  reverse-proxy:
    image: httpd:2.4
    container_name: apache-boundary-reverse-proxy
    hostname: localhost
    ports:
      - 443:443
    volumes:
      - ./configs/reverse-proxy.conf:/usr/local/apache2/conf/httpd.conf
      - /etc/docker-certs:/usr/local/apache2/conf/certs
      - ./proxy-logs:/usr/local/apache2/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:172.20.0.1"

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
        gateway: 172.20.0.1
